
title: POC
email: your-email@example.com
description: ""
url: "example.com" 
twitter: MaasaiSafaris
data-tweet-limit: 1
collections:
  docs:
    output: true
    permalink: /docs/:path/
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
pagination:
  enabled: true
  debug: false
  per_page: 15
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: true
    slugify:
      mode: ascii
      cased: true
    layouts:
      - "categories.html"
    title: ":cat" # :cat is replaced by the categories name
    permalink: "/category/:cat/"
  collections:
    permalink: /:coll/
    enabled: true
    slugify:
      mode: ascii
      cased: true
    layouts:
      - "collections.html"
    title: ":coll"
  tags:
    enabled: false

sass:
  style: expanded

include:
  - _pages
  - _docs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      author: "John Doe"
      kind: "article"
      layout: "post"
      permalink: /:title/
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "tour"
      author: "John Doe"
      permalink: /docs/:title/
  